name: Generate snake animation

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"

  workflow_dispatch:

  push:
    branches:
    - master

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    
      - name: generate snake.svg
        uses: Platane/snk/svg-only@v2
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg

      - name: Pushing dist directory to output branch
        run: |
          git config user.name "MattMori"
          git config user.email "mateus5310@live.com"
          git add .
          git commit -m "Update GitHub Pages"
          git push --force https://github.com/MattMori/MattMori output
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

