name: Generate snake animation

on:
  schedule: 
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Instalar dependências
        run: npm install

      - name: Gerar snake.svg
        run: npm run generate-svg

      - name: Configurar Git e fazer commit
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add dist/snake.svg
          git commit -m "Atualizar animação da cobra"
          git push origin master:output
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
